# Generated by Django 3.2.7 on 2021-09-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacunacion',
            name='id',
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='id_vacunacion',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
